### PR TITLE
ZNTA-1231: check translations overwrite

### PR DESCRIPTION
**Pull request by sdp5**
[ZNTA-1231](https://zanata.atlassian.net/browse/ZNTA-1231) - Drupal plugin overwrites translations when it should not.

@davidmason Please have a look.

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/tmgmt_zanata/11)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tmgmt_zanata.connector.inc, line 528 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11#-KNk3lYpUpeAQQKLua-y:-KNk3lYpUpeAQQKLua-z:-86262171) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/9ab7bea4f7cebb99681d1b336f9d8febc1f874e6/tmgmt_zanata.connector.inc#L528)):*
> ```SourcePawn
>       // no existing translations found. Probably don't need a log message.
>       return FALSE;
>     }
> ```

Can we move this check up above the `$trans_data` line so that it is just the following?

```php
if (!$this->sendtrans) {
  return FALSE;
}

$trans_data = $this->getExistingTransData($job_item)
```

Or would that cause a problem if `$trans_data` is not set to `NULL`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11)*

**Comment by davidmason** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11)*

**Comment by sundeep-co-in** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tmgmt_zanata.connector.inc, line 528 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11#-KNk3lYpUpeAQQKLua-y:-KNkAXdc1HBllzF39ooj:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/9ab7bea4f7cebb99681d1b336f9d8febc1f874e6/tmgmt_zanata.connector.inc#L528)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Can we move this check up above the `$trans_data` line so that it is just the following?
> 
> ```php
> if (!$this->sendtrans) {
>   return FALSE;
> }
> 
> $trans_data = $this->getExistingTransData($job_item)
> ```
> 
> Or would that cause a problem if `$trans_data` is not set to `NULL`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11)*

**Comment by davidmason** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/11#-:-KNlGKIr-WYVIhhXB-K_:1417088721)*

**Comment by djansen-redhat** [comment]
I believe this is working as intended

**Pull request merged**
