### PR TITLE
ZNTA-1087, ZNTA-1088, ZNTA-1089, ZNTA-1123

### PR DESCRIPTION
**Pull request by sundeep-co-in**
[ZNTA-1087](https://zanata.atlassian.net/browse/ZNTA-1087) - Incorrect Zanata links generated in new translation job
[ZNTA-1088](https://zanata.atlassian.net/browse/ZNTA-1088) - Drupal Plugin's auto generated email to be sent to requestor, too
[ZNTA-1089](https://zanata.atlassian.net/browse/ZNTA-1089) - Improve html handling from Drupal plugin
[ZNTA-1123](https://zanata.atlassian.net/browse/ZNTA-1123) - Drupal Plug-In Auto-generated email to include Requestor information

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/tmgmt_zanata/8)

### CODE REVIEW

**Comment by davidmason** [comment]
This looks fine to me. I will ask @djansen to verify, then make a patch release.

**Comment by sundeep-co-in** [comment]
Added some changes. @davidmason Please have a look.

**Comment by davidmason** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by davidmason** [comment]
:lgtm:

<details><summary><i>Previously, sundeep-co-in (Sundeep Anand) wrote…</i></summary>
> Added some changes. @davidmason Please have a look.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-:-KIaawug1Oy89ABHMNJU:1417088721)*

**Comment by davidmason** [comment]
+ON_QA

<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-:-KIab7A7a1V0sLhXuuhN:960103530)*

**Comment by davidmason** [comment]
Reviewed 1 of 8 files at r4.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tmgmt_zanata.connector.inc, line 145 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK3OuR0biVWIXaEeka:-KJK3OuR0biVWIXaEekb:-459693171) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.connector.inc#L145)):*
> ```SourcePawn
>                 'application/octet-stream', 'application/octet-stream'
>             );
>             $response = $this->restclient->process_request($url, $options, true);
> ```

This will only store the last response in the `foreach`, so instead make it an array to capture them all.

---

*[tmgmt_zanata.connector.inc, line 677 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK47xlOQE8oechf0QH:-KJK47xmK-H4rnrQBb3l:-1097300091) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.connector.inc#L677)):*
> ```SourcePawn
>    */
>   private function determineNodeContentFormat($job_item) {
>     $html_content = null;
> ```

This variable looks unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by sundeep-co-in** [comment]
*[tmgmt_zanata.connector.inc, line 677 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK47xlOQE8oechf0QH:-KJK7bEor0ob-r8t2Dmo:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.connector.inc#L677)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> This variable looks unused.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by davidmason** [comment]
Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tmgmt_zanata.utils.inc, line 41 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK7QVinCrIvLThtotn:-KJK7QVinCrIvLThtoto:1790696416) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.utils.inc#L41)):*
> ```SourcePawn
>                     $this->node_head = $field_details; break;
>                 case 'body':
>                     $this->node_body = $field_details; break;
> ```

We should keep all the `break;` statements on a separate line, so it is more consistent with the rest of Zanata's code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by sundeep-co-in** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tmgmt_zanata.connector.inc, line 145 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK3OuR0biVWIXaEeka:-KJZvLNfCYlsbwZiPs91:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.connector.inc#L145)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> This will only store the last response in the `foreach`, so instead make it an array to capture them all.
</details>
Done.

---

*[tmgmt_zanata.utils.inc, line 41 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8#-KJK7QVinCrIvLThtotn:-KJZvGPpWUpT0S1PKsTQ:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/14644c2047723f69d748baafb745c9493c426620/tmgmt_zanata.utils.inc#L41)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> We should keep all the `break;` statements on a separate line, so it is more consistent with the rest of Zanata's code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by davidmason** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/8)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested.
This looks good, @sundeep-co-in - apologies for the delay.

**Pull request merged**
