### PR TITLE
ZNTA-1077: Too many Email notification for single translation job

### PR DESCRIPTION
**Pull request by sundeep-co-in**
[ZNTA-1077](https://zanata.atlassian.net/browse/ZNTA-1077) - Too many Email notification for single translation job

@davidmason Please have a look.
@djansen-redhat Please disable [tmgmt_express_checkout](https://www.drupal.org/project/tmgmt_express_checkout) while testing this patch as it is clubbed with [tmgmt_zanata](https://www.drupal.org/project/tmgmt_zanata) module itself and hence we have some new configurations regarding emails/notification. Now, user is presented with three options: (1) disable notification (2) express checkout - one email for multiple languages (3) normal checkout - emails per language. Things we need to test may be are:
- enable/disable notification
- one email for multiple languages in case of express checkout
- emails per language as we continue submitting jobs in case of normal checkout

 

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/tmgmt_zanata/9)

### CODE REVIEW

**Comment by davidmason** [comment]
Copying tmgmt_express_checkout into this module should have been a separate change on its own, or at least a separate commit. Having both changes mixed together makes it harder to review.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tmgmt_zanata.connector.inc, line 1062 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLK9Ht2HOdVCg0GILSO:-KLK9Ht2HOdVCg0GILSP:1134120265) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.connector.inc#L1062)):*
> ```SourcePawn
>     // Send email notification
>     $notificationEmail = $this->emailSettings['address'];
>     $emailSubject = 'Translation job submitted to Zanata for '.count($locales).' languages.';
> ```

Add spaces around the `.` operator so it is clear that it is a separate operator.

---

*[tmgmt_zanata.module, line 77 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLK9kY8FnHiComKiY_9:-KLK9kY8FnHiComKiY_A:635671333) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.module#L77)):*
> ```
>  * Implements hook_menu()
>  */
> function tmgmt_zanata_menu() {
> ```

All the express checkout code that has been added here should be in a separate file.  I want to avoid having a single file with hundreds or thousands of lines in it.

Is this all copied from tmgmt_express_checkout directly, or are there changes to it?

---

*[tmgmt_zanata.notification.inc, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKAi_YoRzYogbbEfXg:-KLKAi_Z3z5J7I67aAk2:813651329) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.notification.inc#L45)):*
> ```SourcePawn
>      * @return string           Email Body
>      */
>     public function formatEmailBody($email_contents, $locale, $type="default", $format="PLAIN"){
> ```

It looks like the locales for the notification can now come from either `$email_contents` or from `$locale`. Can we unify these so there is only one way to specify the locales here?

If there is one place for the locales to be specified, we may be able to remove the `$type` parameter and use the same template regardless whether there is 1 locale or multiple locales. Even if we need the conditional, it could just check whether the length of the locales array is 1.

---

*[tmgmt_zanata.ui.inc, line 89 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKBuau0S9vhyEEhxAa:-KLKBuavzA41aGs__NaU:938014665) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.ui.inc#L89)):*
> ```SourcePawn
>         '#options' => array(
>             'express' => t('Express Checkout: lesser emails as this will group docs by languages.'),
>             'default' => t('Normal Checkout: emails created per language basis for a set of docs.'),
> ```

Is it possible to disable email notifications completely with this change? It looks like it used to be possible to uncheck the checkbox, but you can't do that with radio buttons.

Also these options can be presented in a way that is more meaningful to users:

 - Do not send email notifications.
 - Send one email when a set of translation jobs is created. The email shows a summary of all the documents and languages that were requested. Users must use express checkout form to allow all requested languages to be listed in a single email.
 - Send one email per language when a set of translation jobs is created.

Is the last sentence in the second point here true? If not, it can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-:-KLK8QydVOygBc3Wk2NB:-366677934)*

**Comment by sundeep-co-in** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[tmgmt_zanata.connector.inc, line 1062 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLK9Ht2HOdVCg0GILSO:-KLRLKDTkkCigcJEuxIj:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.connector.inc#L1062)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Add spaces around the `.` operator so it is clear that it is a separate operator.
</details>
Done.

---

*[tmgmt_zanata.module, line 77 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLK9kY8FnHiComKiY_9:-KLRLNepMMGM_4bC8TgN:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.module#L77)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> All the express checkout code that has been added here should be in a separate file.  I want to avoid having a single file with hundreds or thousands of lines in it.
> 
> Is this all copied from tmgmt_express_checkout directly, or are there changes to it?
</details>
Done.

---

*[tmgmt_zanata.notification.inc, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKAi_YoRzYogbbEfXg:-KLRLS65jFwveRlPlhl_:344499245) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.notification.inc#L45)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> It looks like the locales for the notification can now come from either `$email_contents` or from `$locale`. Can we unify these so there is only one way to specify the locales here?
> 
> If there is one place for the locales to be specified, we may be able to remove the `$type` parameter and use the same template regardless whether there is 1 locale or multiple locales. Even if we need the conditional, it could just check whether the length of the locales array is 1.
</details>
should we keep common email format regardless of checkout type?

---

*[tmgmt_zanata.ui.inc, line 89 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKBuau0S9vhyEEhxAa:-KLRLcaONOd2UgpB40x2:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.ui.inc#L89)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Is it possible to disable email notifications completely with this change? It looks like it used to be possible to uncheck the checkbox, but you can't do that with radio buttons.
> 
> Also these options can be presented in a way that is more meaningful to users:
> 
>  - Do not send email notifications.
>  - Send one email when a set of translation jobs is created. The email shows a summary of all the documents and languages that were requested. Users must use express checkout form to allow all requested languages to be listed in a single email.
>  - Send one email per language when a set of translation jobs is created.
> 
> Is the last sentence in the second point here true? If not, it can be removed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by davidmason** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tmgmt_zanata.checkout.inc, line 10 \[r2\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLTXr0OgYFLHrUnc0YV:-KLTXr0OgYFLHrUnc0YW:-1567646909) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/c01e2b5ec8e7ebb9ababb1a9d398804560d274b1/tmgmt_zanata.checkout.inc#L10)):*
> ```SourcePawn
> 
> /**
>  * Express checkout form, used when there are 2 or more jobs to check out.
> ```

I think this description is wrong now. I think I changed it to be available regardless of the number of jobs. We should change it to be:

```php
/**
 * Express checkout form. Used to specify job name and translator plugin on a single
 * form for a set of languages, instead of one form per language.`
```

---

*[tmgmt_zanata.notification.inc, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKAi_YoRzYogbbEfXg:-KLTW836MsyxaWNypmJd:-1584317785) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.notification.inc#L45)):*
<details><summary><i>Previously, sundeep-co-in (Sundeep Anand) wrote…</i></summary>
> should we keep common email format regardless of checkout type?
</details>
I think we should, yes. It will make our code simpler and will give a consistent experience to people reading the emails.

---

*[tmgmt_zanata.ui.inc, line 89 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKBuau0S9vhyEEhxAa:-KLTWaw-m8lcQ7wB_mPy:-1954645091) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.ui.inc#L89)):*
<details><summary><i>Previously, sundeep-co-in (Sundeep Anand) wrote…</i></summary>
> Done.
</details>
We should move the information about blank email address to the email field, so that would become `'Email address to send to when a job is created. Leave blank to disable email notifications.'`

It would still be clearer to have a separate radio option to send no emails though, and that would allow users to disable emails temporarily without removing the preferred email address from config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by sundeep-co-in** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[tmgmt_zanata.checkout.inc, line 10 \[r2\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLTXr0OgYFLHrUnc0YV:-KLW4AoYrGmkqE3NFL5n:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/c01e2b5ec8e7ebb9ababb1a9d398804560d274b1/tmgmt_zanata.checkout.inc#L10)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think this description is wrong now. I think I changed it to be available regardless of the number of jobs. We should change it to be:
> 
> ```php
> /**
>  * Express checkout form. Used to specify job name and translator plugin on a single
>  * form for a set of languages, instead of one form per language.`
> ```
</details>
Done.

---

*[tmgmt_zanata.notification.inc, line 45 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKAi_YoRzYogbbEfXg:-KLW4DBzhoE9Yfr3W49o:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.notification.inc#L45)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think we should, yes. It will make our code simpler and will give a consistent experience to people reading the emails.
</details>
Done.

---

*[tmgmt_zanata.ui.inc, line 89 \[r1\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KLKBuau0S9vhyEEhxAa:-KLW4EsyQe6xJqW9Oyjy:-499146009) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/8de08569467d75ac2330ef50713aa3aff76120dd/tmgmt_zanata.ui.inc#L89)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> We should move the information about blank email address to the email field, so that would become `'Email address to send to when a job is created. Leave blank to disable email notifications.'`
> 
> It would still be clearer to have a separate radio option to send no emails though, and that would allow users to disable emails temporarily without removing the preferred email address from config.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by davidmason** [comment]
This all looks good to me. Please proceed to QA with this, and make sure there is a list of the new config options on the main PR description (so they know what to test).

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-:-KL_GIGUfD71CydpmL5x:1402268900)*

**Comment by sundeep-co-in** [comment]
@djansen-redhat Please proceed with testing this patch.

**Comment by djansen-redhat** [comment]
@sundeep-co-in  @davidmason When starting up, I get this (some lines got cut by Drupal's text):
```
Watchdog: Notice: Undefined property: stdClass::$name in TMGMTZanataTranslatorNotification->__construct() (line 31 of /var/www/html/quick-drupal/sample-drupal/drupal/sites/all/moLog intmgmt_zanata/tmgmt_zanata.notification.inc). | severity: 5 | type: php | uid: 0 | 127.0.0.1 | http://127.0.0.1:8888/ |  |
 
Watchdog: Notice: Undefined property: stdClass::$mail in TMGMTZanataTranslatorNotifiline 32 of /var/www/html/quick-drupal/sample-drupal/drupal/sites/all/modules/tmgmt_zanata/tmgmt_zanata.notification.inc). | severity: 5 | type: php | uid: 0 | 127.0.0.1 | http://127.0.0.1:8888/ |  |
 
tdClass::$name in TMGMTZanataTranslatorNotification->__construct() (line 31 of /var/www/html/quick-drupal/sample-drupal/drupal/sites/all/modules/tmgmt_zanata/tmgmt_zanat   Powered by Drupal | severity: 5 | type: php | uid: 0 | 127.0.0.1 | http://127.0.0.1:8888/ |  |
 
Watchdog: Notice: Undefined property: stdClass::$mail in TMGMTZanataTranslatorNotification->__construct() (line 32 of /var/www/html/quick-drupal/sample-drupal/drupal/sites/all/modules/tmgmt_zanata/tmgmt_zanata.notification.inc). | severity: 5 | type: php | uid: 0 | 127.0.0.1 | http://127.0.0.1:8888/ |  |
```

**Comment by davidmason** [comment]
Looks like the `global $user` is not populated with name or email when the notification class is being constructed. I do not see why it would be constructed at startup though.

- Could the order of the `files[]` in tmgmt_zanata.info contribute to this?
- Do we need an added check to make sure the user is set up before generating notifications?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-:-KM1y0LhilpnnI6wKb50:-2038983724)*

**Comment by djansen-redhat** [comment]
Also, it appears the mail is being sent to the admin user (or logged in user) rather than the user specified in the Translation Management Translator config.

**Comment by sundeep-co-in** [comment]
@davidmason Please review the change. @djansen-redhat Yes, this is intended. Added in https://github.com/zanata/tmgmt_zanata/pull/8 as per [ZNTA-1088](https://zanata.atlassian.net/browse/ZNTA-1088)

**Comment by davidmason** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tmgmt_zanata.notification.inc, line 63 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KM2_qNaTAUlkPxs9z41:-KM2_qNaTAUlkPxs9z42:-1328464577) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/c5d2f147929d620c5daebc7b8972e3b3e0ca4743/tmgmt_zanata.notification.inc#L63)):*
> ```SourcePawn
>             $msgBody .= "Name: ".$this->requesterName."\n";
>             $msgBody .= "Email: ".$this->requesterEmail."\n";
>         }
> ```

Does this mean some emails will be sent without requester information? It seems strange that this situation could ever happen since someone would need to be signed in to make the request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by sundeep-co-in** [comment]
*[tmgmt_zanata.notification.inc, line 63 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KM2_qNaTAUlkPxs9z41:-KM2czM7cOmJlxdTpZV5:-932061649) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/c5d2f147929d620c5daebc7b8972e3b3e0ca4743/tmgmt_zanata.notification.inc#L63)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Does this mean some emails will be sent without requester information? It seems strange that this situation could ever happen since someone would need to be signed in to make the request.
</details>
check is just to hide watchdog notice, emails will contain requester info every time! I guess its cron which instantiate notification and hence no name and email for user object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tmgmt_zanata.notification.inc, line 63 \[r4\]](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9#-KM2_qNaTAUlkPxs9z41:-KM2exKolxTYrSleKIGA:-1719993741) ([raw file](https://github.com/zanata/tmgmt_zanata/blob/c5d2f147929d620c5daebc7b8972e3b3e0ca4743/tmgmt_zanata.notification.inc#L63)):*
<details><summary><i>Previously, sundeep-co-in (Sundeep Anand) wrote…</i></summary>
> check is just to hide watchdog notice, emails will contain requester info every time! I guess its cron which instantiate notification and hence no name and email for user object.
</details>
That's fine then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/tmgmt_zanata/9)*

**Comment by djansen-redhat** [comment]
The errors are gone.
I'm still seeing individual emails per locale for jobs.

**Pull request merged**
